### PR TITLE
Update nix packaging to be more idiomatic

### PR DESCRIPTION
**Pull request by SEbbaDK**
# Motivation

The current naming and packaging, stops automatic runtime requirements from being included.
Using default.nix also allows import of the repo, without specifying the .nix file.

# Things done

- Rename `nordvpn.nix` to `default.nix`
- Change derivation to use `mkDerivation`
- Change imports to allow overriding via `nordvpn.override`

### CODE REVIEW

**Comment by SEbbaDK** [comment]
Ohh, maybe `{ inherit pkgs; }` could be `pkgs` like in the original nix file (in regards to README.md)

**Comment by wanieru** [comment]
Feel free to update README.md as well! Even though unzip, wget and openvpn can be included as build inputs, this would still require users to have them in their path, right?
Will probably merge later tonight.

**Comment by SEbbaDK** [comment]
> would still require users to have them in your path

Yes, but it will specify when building with a deployment tools that those packages are required for the runtime. The path thing needs to be fixed with something like `makeWrapper`.

**Comment by SEbbaDK** [comment]
I added wrapping so that a PATH with the required dependencies are set up

**Pull request merged**
